language: node_js
node_js: '10'
cache: yarn
env: YARN_GPG=no
branches:
  only:
    - master
addons:
  apt:
    packages:
      - latexmk
      - texlive-full
script:
  - latexmk -pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
